import { Component } from '@angular/core';
import { MaterialModule } from '../../shared/material.module';
import { Car, Engine, Transmission } from '../../models/car.interface';
import { Building } from '../../models/building.interface';
import { BasicObject } from '../../models/basic-object.interface';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-offer-item',
  standalone: true,
  imports: [CommonModule, MaterialModule],
  templateUrl: './offer-item.component.html',
  styleUrl: './offer-item.component.scss',
})
export class OfferItemComponent {
  listItems: (Car | Building | BasicObject)[] = [
    {
      id: 'a',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'aff',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'att',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'arr',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'aee',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'aww',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'aqq',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'ass',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'add',
      name: 'Volkswagen T-Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5 Roc 1.5',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'as',
      name: 'Volkswagen T-Roc 1.5 TSI DSG 110 kW',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
    {
      id: 'asd',
      name: 'Volkswagen T-Roc 1.5 TSI DSG 110 kW',
      model: '1.5 TSI DSG',
      brand: 'Volkswagen',
      image: ['https://storage.alpha-analytics.cz/resize/a58fb3f2-706b-45a5-9fd1-b3e7101e5ad9?ts=1729938317&width=277&height=208&fit=cover&withoutEnlargement=false'],
      price: 28399,
      mileage: 57617,
      productionYear: '2021',
      modelYear: '2021',
      engineSize: 1.5,
      location: 'Zagreb',
      description:
        'A well-maintained SUV with a powerful engine and automatic transmission, ideal for city and highway driving.',
      power: 110,
      engine: Engine.DIESEL,
      transmission: Transmission.AUTOMATIC,
    },
  ];

  get cars(): Car[] {
    return this.listItems.filter((item): item is Car => 'engine' in item);
  }
}
